# Worthwhile Secret audio source
enabled=true
download_dir=/data/braillatron/music/worthwhile
credentials_path=/data/braillatron/credentials/worthwhile.ini
cookie_jar_path=/data/braillatron/credentials/worthwhile.cookies
search_limit=20
