.PHONY: list-tests

list-tests:
	@printf '%-32s %-34s %s\n' 'TARGET' 'COVERAGE' 'DEPS'
	@printf '%-32s %-34s %s\n' 'braillatron-motion-test' 'kinematics math' 'none'
	@printf '%-32s %-34s %s\n' 'braillatron-motion-gate-sync-test' 'motion gate / telemetry sync' 'none'
	@printf '%-32s %-34s %s\n' 'braillatron-host-chord-test' 'evdev chord assembly' 'none'
	@printf '%-32s %-34s %s\n' 'braillatron-wikipedia-test' 'Wikipedia HTTP client' 'none (stub network)'
	@printf '%-32s %-34s %s\n' 'braillatron-audio-output-test' 'platform audio output' 'none'
	@printf '%-32s %-34s %s\n' 'braillatron-display-test' 'wired UI chrome backends' 'ncurses'
	@printf '%-32s %-34s %s\n' 'braillatron-remote-display-test' 'wireless display + pairing' 'none (in-process)'
	@printf '%-32s %-34s %s\n' 'braillatron-connect-test' 'connectd async IPC client' 'none (stub)'
	@printf '%-32s %-34s %s\n' 'braillatron-ui-test' 'UI shell integration' 'ncurses (display backends)'
	@printf '%-32s %-34s %s\n' 'braillatron-timer-test' 'TimerService' 'none'
	@printf '%-32s %-34s %s\n' 'braillatron-dictionary-test' 'SQLite dictionary store' 'libsqlite3'
	@printf '%-32s %-34s %s\n' 'braillatron-spelling-test' 'spelling list store' 'none'
	@printf '%-32s %-34s %s\n' 'braillatron-contacts-test' 'contacts address book' 'none'
	@printf '%-32s %-34s %s\n' 'braillatron-music-test' 'music backend + mpv IPC' 'none (stub subprocess)'
	@printf '%-32s %-34s %s\n' 'braillatron-weather-test' 'weather geocoding backend' 'none (stub)'
	@printf '%-32s %-34s %s\n' 'braillatron-podcasts-test' 'podcast RSS + mpv IPC' 'none (stub)'
	@printf '%-32s %-34s %s\n' 'braillatron-radio-test' 'radio stream backend' 'none (stub)'
	@printf '%-32s %-34s %s\n' 'braillatron-library-test' 'library document store' 'none'
	@printf '%-32s %-34s %s\n' 'braillatron-library-backend-test' 'library network backend' 'none (stub)'
	@printf '%-32s %-34s %s\n' 'braillatron-worthwhile-test' 'Worthwhile Secret backend' 'none (stub)'
	@printf '%-32s %-34s %s\n' 'braillatron-gmail-test' 'Gmail backend' 'none (stub)'
	@printf '%-32s %-34s %s\n' 'braillatron-calculator-test' 'calculator app logic' 'none'
	@printf '%-32s %-34s %s\n' 'braillatron-liblouis-test' 'braille translation bridge' 'liblouis (check-liblouis only)'
